### ISSUE TITLE
点击运行后无法显示界面

### ISSUE THREAD

**Issue by mdhhxtc** [ping11700/LOLKit#103]
点击运行后无法显示界面，任务里管理器中可以看到进程运行。该bug间接性出现，之前重启可解决，更新252后第一次运行成功，之后均无法显示界面。

**Screenshots**
![image](https://github.com/ping11700/LOLKit/assets/67906386/16a397ba-c2de-47e9-a15d-84c75cad9515)
![image](https://github.com/ping11700/LOLKit/assets/67906386/6962182b-94cd-4aba-9b2e-d6f356524cbf)

**Desktop (please complete the following information):**
版本	Windows 11 专业版
版本	23H2
安装日期	‎2024/‎4/‎30
操作系统版本	22631.3593
序列号	MP2NJAWA
体验	Windows Feature Experience Pack 1000.22700.1003.0

**Comment by mdhhxtc** [comment]
补充日志：
19:04:05[Info]: ************* LOLKit启动 v2.5.2 *************
19:04:05[Info]: 自动检测到游戏路径: d:\program files\lol\tcls\client.exe
19:04:05[Fatal]-APP.Fatal: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 CRNAi26I4GFLjwcyrQQ.L8HEDi6WJfIvwtdfCdB..ctor()
   在 u2PpFVkjtYdwocA4JpX.WbWVACkoYSQFLoLLNaE.iALkdPNMsw()
   在 OHNR5uyaCN6NgPe7SN.EqB2afq0pb1oMKUGPU.XLBHtTPXxu4Xk6CabpnA(Object )
   在 OHNR5uyaCN6NgPe7SN.EqB2afq0pb1oMKUGPU.OnStartup(StartupEventArgs  )
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
19:04:10[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:04:15[Error]-GetP: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.QVbBTQPqEHWUokE4BSAg(Object , Object )
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.u5pMpp3dtA()
19:04:25[Error]-GetP: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.QVbBTQPqEHWUokE4BSAg(Object , Object )
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.u5pMpp3dtA()
19:04:26[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:04:35[Error]-GetP: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.QVbBTQPqEHWUokE4BSAg(Object , Object )
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.u5pMpp3dtA()
19:04:41[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:04:56[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:05:12[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:05:29[Info]: ************* LOLKit启动 v2.5.2 *************
19:05:29[Info]: 自动检测到游戏路径: d:\program files\lol\tcls\client.exe
19:05:29[Fatal]-APP.Fatal: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 CRNAi26I4GFLjwcyrQQ.L8HEDi6WJfIvwtdfCdB..ctor()
   在 u2PpFVkjtYdwocA4JpX.WbWVACkoYSQFLoLLNaE.iALkdPNMsw()
   在 OHNR5uyaCN6NgPe7SN.EqB2afq0pb1oMKUGPU.XLBHtTPXxu4Xk6CabpnA(Object )
   在 OHNR5uyaCN6NgPe7SN.EqB2afq0pb1oMKUGPU.OnStartup(StartupEventArgs  )
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
19:05:34[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:05:39[Error]-GetP: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.QVbBTQPqEHWUokE4BSAg(Object , Object )
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.u5pMpp3dtA()
19:05:49[Error]-GetP: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.QVbBTQPqEHWUokE4BSAg(Object , Object )
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.u5pMpp3dtA()
19:05:50[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:05:59[Error]-GetP: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.QVbBTQPqEHWUokE4BSAg(Object , Object )
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.u5pMpp3dtA()
19:06:05[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:06:14[Error]-GetP: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.QVbBTQPqEHWUokE4BSAg(Object , Object )
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.u5pMpp3dtA()
19:07:17[Info]: ************* LOLKit启动 v2.5.2 *************
19:07:17[Info]: 自动检测到游戏路径: d:\program files\lol\tcls\client.exe
19:07:17[Fatal]-APP.Fatal: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 CRNAi26I4GFLjwcyrQQ.L8HEDi6WJfIvwtdfCdB..ctor()
   在 u2PpFVkjtYdwocA4JpX.WbWVACkoYSQFLoLLNaE.iALkdPNMsw()
   在 OHNR5uyaCN6NgPe7SN.EqB2afq0pb1oMKUGPU.XLBHtTPXxu4Xk6CabpnA(Object )
   在 OHNR5uyaCN6NgPe7SN.EqB2afq0pb1oMKUGPU.OnStartup(StartupEventArgs  )
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
19:07:22[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:07:27[Error]-GetP: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.QVbBTQPqEHWUokE4BSAg(Object , Object )
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.u5pMpp3dtA()
19:07:37[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:07:53[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:08:08[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:08:23[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:08:38[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:08:53[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:09:09[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:09:28[Info]: ************* LOLKit启动 v2.5.2 *************
19:09:28[Info]: 自动检测到游戏路径: D:\Program Files\LOL\TCLS\Client.exe
19:09:28[Fatal]-APP.Fatal: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 CRNAi26I4GFLjwcyrQQ.L8HEDi6WJfIvwtdfCdB..ctor()
   在 u2PpFVkjtYdwocA4JpX.WbWVACkoYSQFLoLLNaE.iALkdPNMsw()
   在 OHNR5uyaCN6NgPe7SN.EqB2afq0pb1oMKUGPU.XLBHtTPXxu4Xk6CabpnA(Object )
   在 OHNR5uyaCN6NgPe7SN.EqB2afq0pb1oMKUGPU.OnStartup(StartupEventArgs  )
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
19:09:33[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:09:38[Error]-GetP: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.QVbBTQPqEHWUokE4BSAg(Object , Object )
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.u5pMpp3dtA()
19:09:48[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:10:04[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:10:19[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:10:34[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:10:49[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:11:04[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:11:20[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:11:35[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:11:50[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:12:05[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:12:21[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:12:36[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:13:00[Info]: ************* LOLKit启动 v2.5.2 *************
19:13:00[Info]: 自动检测到游戏路径: D:\Program Files\LOL\TCLS\Client.exe
19:13:00[Fatal]-APP.Fatal: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 CRNAi26I4GFLjwcyrQQ.L8HEDi6WJfIvwtdfCdB..ctor()
   在 u2PpFVkjtYdwocA4JpX.WbWVACkoYSQFLoLLNaE.iALkdPNMsw()
   在 OHNR5uyaCN6NgPe7SN.EqB2afq0pb1oMKUGPU.XLBHtTPXxu4Xk6CabpnA(Object )
   在 OHNR5uyaCN6NgPe7SN.EqB2afq0pb1oMKUGPU.OnStartup(StartupEventArgs  )
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
19:13:05[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:13:10[Error]-GetP: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.QVbBTQPqEHWUokE4BSAg(Object , Object )
   在 Dgx1Q9MmIxagNB5jBpa.BU3purlzqJC7K225hfy.u5pMpp3dtA()
19:13:20[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:13:36[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:13:51[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:14:06[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:14:21[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:14:37[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:14:52[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:15:07[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:15:22[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:15:38[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:15:53[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:16:08[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:16:23[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:16:38[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:16:54[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:17:09[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:17:24[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:17:39[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:17:55[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:18:10[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:18:25[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:18:40[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:18:56[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:19:11[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:19:26[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:19:41[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()
19:19:57[Error]-Flow_Lcu.Start: can't read right token and port
   在 IffKjFbBI1gE7acokVv.hglpMPbbOxaH10nPPkf.<<Start>b__6_0>d.MoveNext()

**Comment by ping11700** [comment]
kill进程, config删除 试试.

**Comment by mdhhxtc** [comment]
> kill进程, config删除 试试.

可以了，但是每次都需要删除config才能启动成功。

**Comment by ping11700** [comment]
下个版本修复

**Comment by ping11700** [comment]
done

**Comment by mdhhxtc** [comment]
> done

没问题了🥰
