### ISSUE TITLE
一些显示问题反馈

### ISSUE THREAD

**Issue by z1298808165** [ping11700/LOLKit#107]
1.战绩那个窗口面板，点击关闭后实则在任务栏的窗口中还能看到，没有关闭。

2.对局双方信息在游戏内查看时容易卡屏。因使用习惯问题，我wegame一直是启用的，在游戏内查看对局双方信息时，大概率会把wegame的面板给卡住取消不了。另外在查看对局双方信息时可能会切出游戏，只要发生切出游戏的情况后，只能退出软件重新打开，尝试看看会不会再切出游戏。

3.车队信息查询有误，判断了和我非开黑的队友为一个车队，自家车队大概率是2~3人一个车队，对方4~5人一个车队（仅完了大乱斗）

**Comment by ping11700** [comment]
done, 车队判断非100%正确.
