### ISSUE TITLE
is:issue is:open 能不能把快捷键设置给出来，我现在没有  键位“~”不能玩，一直给我切屏，很影响使用

### ISSUE THREAD

**Issue by Zyb-iot** [ping11700/LOLKit#108]
> [!NOTE]
> issue中是否已经包含(包括closed issue).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ping11700** [comment]
done

**Comment by zhaoxiaozhao07** [comment]
'~'键切屏太影响使用了，每次玩，不小心碰到直接切屏出去，气死人

**Comment by ping11700** [comment]
done
