### ISSUE TITLE
必须付费使用吗？c

### ISSUE THREAD

**Issue by Inte56grity** [ping11700/LOLKit#110]
> [!NOTE]
> issue中是否已经包含(包括closed issue).

**Describe the solution you'd like**

**Comment by Doctorlee0827** [comment]
更新后确实只能付费使用了

**Comment by yll007007** [comment]
1个月8块也太高了点

**Comment by ping11700** [comment]
后面调用付费API, 提供高带宽下载服务, 不再把精力放在区分vip模式上, github应该有很多这样的项目, 也可以试试

**Comment by xiaomohen2023** [comment]
没有自愿捐助吗，月费8元/年费90元，感觉有点高啊，我每天也用不了1小时...
