### ISSUE TITLE
推荐出装应用问题

### ISSUE THREAD

**Issue by z1298808165** [ping11700/LOLKit#117]
最近老是出现无法应用出装的情况，而且之前自动应用的提示也没有了，日志如下

22:28:47[Fatal]-APP.Fatal: 只有在任务处于完成状态(RanToCompletion、Faulted 或 Canceled)时才能释放它。
   在 System.Threading.Tasks.Task.Dispose(Boolean disposing)
   在 yr2nD2Vgx6Lf8cQNqRc.oDlF5DVd8PhRtSP1d6Y.<<LoopConnect>b__13_0>d.wOsf5kcoVwIupYI9ZOMX(Object )
   在 yr2nD2Vgx6Lf8cQNqRc.oDlF5DVd8PhRtSP1d6Y.<<LoopConnect>b__13_0>d.MoveNext()
22:29:01[Error]-LoadAnalysis: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 OZ96ooiehNcWKlVAwQL.XEYlkoig42Tt9S08goN.LoadAnalysis(String position)
22:29:01[Error]-SetItem: 值不能为 null。
参数名: path
   在 System.IO.DirectoryInfo..ctor(String path)
   在 OZ96ooiehNcWKlVAwQL.XEYlkoig42Tt9S08goN.SetItem()
22:29:06[Error]-LoadAnalysis: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 OZ96ooiehNcWKlVAwQL.XEYlkoig42Tt9S08goN.LoadAnalysis(String position)
22:29:09[Error]-LoadAnalysis: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 OZ96ooiehNcWKlVAwQL.XEYlkoig42Tt9S08goN.LoadAnalysis(String position)
22:29:39[Error]-LoadAnalysis: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 OZ96ooiehNcWKlVAwQL.XEYlkoig42Tt9S08goN.LoadAnalysis(String position)
22:29:39[Error]-SetItem: 值不能为 null。
参数名: path
   在 System.IO.DirectoryInfo..ctor(String path)
   在 OZ96ooiehNcWKlVAwQL.XEYlkoig42Tt9S08goN.SetItem()
22:29:43[Error]-LoadAnalysis: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 OZ96ooiehNcWKlVAwQL.XEYlkoig42Tt9S08goN.LoadAnalysis(String position)

22:29:45[Error]-SetItem: 值不能为 null。
参数名: path
   在 System.IO.DirectoryInfo..ctor(String path)
   在 OZ96ooiehNcWKlVAwQL.XEYlkoig42Tt9S08goN.SetItem()
22:29:45[Error]-LoadAnalysis: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 OZ96ooiehNcWKlVAwQL.XEYlkoig42Tt9S08goN.LoadAnalysis(String position)
22:29:46[Error]-SetItem: 值不能为 null。
参数名: path
   在 System.IO.DirectoryInfo..ctor(String path)
   在 OZ96ooiehNcWKlVAwQL.XEYlkoig42Tt9S08goN.SetItem()
22:29:58[Error]-SetItem: 值不能为 null。
参数名: path
   在 System.IO.DirectoryInfo..ctor(String path)
   在 OZ96ooiehNcWKlVAwQL.XEYlkoig42Tt9S08goN.SetItem()
22:29:59[Error]-SetItem: 值不能为 null。
参数名: path
   在 System.IO.DirectoryInfo..ctor(String path)
   在 OZ96ooiehNcWKlVAwQL.XEYlkoig42Tt9S08goN.SetItem()

**Comment by z1298808165** [comment]
似乎是文件夹不存在导致的，因为出装有点杂乱，我就把Global文件夹删除了😂
\Game\Config\Global\Recommended

**Comment by z1298808165** [comment]
另外能否将推荐出装应用至对应英雄，对应路径如下
\Game\Config\Champions\英雄名\Recommended\推荐出装.json

例如阿木木：\Game\Config\Champions\Amumu\Recommended\[OP.GG 大乱斗]-Amumu-ARAM.json

**Comment by ping11700** [comment]
出装有特定的文件路径，lolkit可以满足选择英雄时，实时出装。无需缓存到本地。
