### ISSUE TITLE
账号的框无法输入 密码可以正常输入

### ISSUE THREAD

**Issue by puzzle9** [ping11700/LOLKit#118]
![image](https://github.com/user-attachments/assets/0acacac2-e037-4bde-acb6-7b98cf6b8884)
![image](https://github.com/user-attachments/assets/d92299cd-fd33-4882-b0fb-2afb9f0f3a49)

**Comment by ping11700** [comment]
更新最新版本

**Comment by puzzle9** [comment]
更新到了 2.9.7
![image](https://github.com/user-attachments/assets/efbc8623-79e6-4955-9b5a-fd8c3a15e7a9)
现在点击 游戏账号输入框弹出这个
这个是功能要支付后才能使用吗

**Comment by ping11700** [comment]
是的
