### ISSUE TITLE
不支持请求的安全协议。

### ISSUE THREAD

**Issue by nosiyBUGS** [ping11700/LOLKit#119]
> [!NOTE]
> issue中是否已经包含(包括closed issue).

23:08:29[Info]: ************* LOLkit启动 v2.9.6 *************
23:08:29[Info]: 检测到游戏路径: c:\wegameapps\英雄联盟\tcls\client.exe
23:08:30[Fatal]-APP.Fatal: 不支持请求的安全协议。
   在 System.Net.ServicePointManager.ValidateSecurityProtocol(SecurityProtocolType value)
   在 jpABRCw5UcajrbKyQN6.t5kUDJw4pDWv6ZulC3Y.X4wgDB1nS34jAhBu94ko(SecurityProtocolType )
   在 jpABRCw5UcajrbKyQN6.t5kUDJw4pDWv6ZulC3Y..ctor()
   在 jpABRCw5UcajrbKyQN6.t5kUDJw4pDWv6ZulC3Y.<>c.KEOa3J8wILw()
   在 System.Lazy`1.CreateValue()
   在 System.Lazy`1.LazyInitValue()
   在 jpABRCw5UcajrbKyQN6.t5kUDJw4pDWv6ZulC3Y.jDtwXeCy1p()
   在 MnI95TQlOjXgFK1Oer.jbCYNrykdEAeZdERKN.OnStartup(StartupEventArgs  )
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by nosiyBUGS** [comment]
系统版本 LSTC 1809 Windows10

**Comment by ping11700** [comment]
不能用吗? 还是什么情况, 远程debug 看看

**Comment by nosiyBUGS** [comment]
可以远程我的电脑看看 用todesk吗

**Comment by ping11700** [comment]
加一下群,  沟通及时, 主页有

**Comment by ping11700** [comment]
done
