### ISSUE TITLE
功能太多花里胡哨的,应该分类一下

### ISSUE THREAD

**Issue by kiki0s** [ping11700/LOLkit#121]
我为了评论还要创个号.
我下载这个应用就是为了当启动器,都有slfn盒子了,也不需要这么多功能,你应该出个清爽版,只有登录和删除wegame的功能就行了,各种各样的别的功能你应该打成一个扩展包,让用户自己选择用不用就好了.(可以加一个打野记时因为萨勒芬妮没有哈哈哈)

**Comment by ping11700** [comment]
hi there,  free模式下就是你说的哪些功能哦
