### ISSUE TITLE
无法跳过wegame，提示需要下载wegame

### ISSUE THREAD

**Issue by sumerise** [ping11700/LOLKit#13]
![9Z(`KY) EWA4Q{2)2WYV~{D](https://github.com/ping11700/LOLKit/assets/125735756/9898323b-eddf-41af-9e1e-158af1a403a8)

**Comment by sumerise** [comment]
重试很多遍没用

**Comment by ping11700** [comment]
卡死指的是?

**Comment by ping11700** [comment]
1.6.0 点击 自动修复 功能
