### ISSUE TITLE
load script file failed

### ISSUE THREAD

**Issue by CarryLeeS** [ping11700/LOLKit#14]
启动游戏显示load script file failed(没有通过软件下载)
![image](https://github.com/ping11700/LOLKit/assets/96744288/a874c96b-395c-4868-9b78-72b3ea9af20f)

**Comment by ping11700** [comment]
这是lol client客户端 lua脚本错误., 可尝试直接启动client.exe

**Comment by ping11700** [comment]
使用lolkit 重新安装

**Comment by jokervTv** [comment]
使用lolkit重新安装无法解决

**Comment by ping11700** [comment]
重新安装LOL没有解决吗

**Comment by jokervTv** [comment]
没有，发现 `tcls\ui\script` 这个文件夹并不存在，用 wegame 修复以后这个文件夹也不会出现，但是 wegame 可以正常启动

**Comment by zhelooo** [comment]
请问解决了吗，实在不想装wegame
