### ISSUE TITLE
程序的TraceWindow开关打开后，位置不对

### ISSUE THREAD

**Issue by w1g2f3** [ping11700/LOLKit#17]
系统是win8.1，
![image](https://github.com/ping11700/LOLKit/assets/19285783/83ca3582-9af2-409b-9355-5a477f9470b2)

**Comment by ping11700** [comment]
没看出问题

**Comment by w1g2f3** [comment]
我来进一步描述下，日志输出背景是透明的，在桌面的背景下很难被发现，截图是因为背景是浏览器新页面，不是桌面。新附上在桌面使用时截图。这样看，是不是就很难发现日志所在了。
![image](https://github.com/ping11700/LOLKit/assets/19285783/374040ff-f3e7-463a-97a4-3faa2364bf5e)

**Comment by ping11700** [comment]
是这样设计的, 不添加taceWindow的背景色, 防止窗体阻挡用户交互
