### ISSUE TITLE
针对密码安全性考量，是否可以支持扫码登录

### ISSUE THREAD

**Issue by Sonessica** [ping11700/LOLKit#18]
no wegame本身功能都挺实用，但第三方无论如何都难以让人放心密码安全，哪怕不开源。
是否可以支持扫码登录以规避这一顾虑。

**Comment by ping11700** [comment]
brilliant，bro
账户安全问题，确实很难搞定，这是一个很好的解决方案。thx

**Comment by kmvan** [comment]
扫码登陆的话，那没法记住登录信息啊。依然每次都要扫码的。

**Comment by Sonessica** [comment]
登录选择方式的扩展，信任安全用记住密码的方式，稳妥保护账号用扫码登录，互不影响

**Comment by ping11700** [comment]
已实现👍
