### ISSUE TITLE
非常感谢UP制作的软件，已经给star，但是不开源还是多少有点让人不放心。

### ISSUE THREAD

**Issue by TianYaDY** [ping11700/LOLKit#19]
是什么安全问题导致不能开源呢？

**Comment by ping11700** [comment]
你好,  自开发这个软件起, 账户的安全问题让我焦头烂额, 自此有了三层安全层, 
1. 舍弃联网, 因而舍弃了绝大部分功能, 也限制了软件的拓展
2. 账户非对称加密
3. 每次登录手动输入密码, 本地不再记录密码
不开源的原因, 想必有过独立开发经验的开发者都知道, 开源后的不可管控性

**Comment by kindleszhang** [comment]
大佬，空口无凭啊。。。

**Comment by ping11700** [comment]
1. 发布快一年了, 没有用户说账号被盗,被封. 
2. 现在国内账号都绑定手机号,  QQ的价值还有多少?
3. 软件free, 高带宽的服务器自费租的.
4. 没人让你用,

**Comment by TianYaDY** [comment]
> 你好, 自开发这个软件起, 账户的安全问题让我焦头烂额, 自此有了三层安全层,
> 
>     1. 舍弃联网, 因而舍弃了绝大部分功能, 也限制了软件的拓展
> 
>     2. 账户非对称加密
> 
>     3. 每次登录手动输入密码, 本地不再记录密码
>        不开源的原因, 想必有过独立开发经验的开发者都知道, 开源后的不可管控性

原来如此。

**Comment by zzhzero** [comment]
请教一下第一次使用要重启电脑的作用是?

**Comment by ping11700** [comment]
> 请教一下第一次使用要重启电脑的作用是?

获取初始化com组件信息

**Comment by ping11700** [comment]
> > 你好, 自开发这个软件起, 账户的安全问题让我焦头烂额, 自此有了三层安全层,
> > ```
> > 1. 舍弃联网, 因而舍弃了绝大部分功能, 也限制了软件的拓展
> > 
> > 2. 账户非对称加密
> > 
> > 3. 每次登录手动输入密码, 本地不再记录密码
> >    不开源的原因, 想必有过独立开发经验的开发者都知道, 开源后的不可管控性
> > ```
> 
> 原来如此。

感谢理解
