### ISSUE TITLE
引导client.exe启动，弹出qq安全中心验证

### ISSUE THREAD

**Issue by ilovecode2018** [ping11700/LOLKit#24]
qq安全中心验证一直加载，然后死掉。对client也只能强行alt+f4

**Comment by ping11700** [comment]
1.6解决此问题,

**Comment by baonujuedoushi** [comment]
我更新1.6.0版本后依旧有此问题，所以我在lolkit界面选择了手动输入密码，然后登录了qq客户端，在lol客户端登录的时候使用了qq快捷登录。

**Comment by ping11700** [comment]
需要使用1.6.0的自动修复功能, 具体看一下B站视频
