### ISSUE TITLE
无法打开，点开就显示lolkit停止工作

### ISSUE THREAD

**Issue by yll007007** [ping11700/LOLKit#25]

**Comment by ping11700** [comment]
补充一下细节 😂

**Comment by yll007007** [comment]
> 补充一下细节 😂

![无标题](https://github.com/ping11700/LOLKit/assets/32213862/f2c166ab-23b7-4d0e-8f62-0139d4528cf5)
就是这样

**Comment by baonujuedoushi** [comment]
我也出现了此问题，可能是因为我在安装新版本的时候选择了覆盖之前旧文件安装，然后就出现了这个问题，同时我的键盘输入也变得很慢很卡。在我删除所有旧文件重新安装后就好了。

**Comment by ping11700** [comment]
> 我也出现了此问题，可能是因为我在安装新版本的时候选择了覆盖之前旧文件安装，然后就出现了这个问题，同时我的键盘输入也变得很慢很卡。在我删除所有旧文件重新安装后就好了。




1. 键盘输入也变得很慢很卡, 这个问题, 我debug 瞅瞅

**Comment by ping11700** [comment]
> > 补充一下细节 😂
> 
> ![无标题](https://user-images.githubusercontent.com/32213862/260273092-f2c166ab-23b7-4d0e-8f62-0139d4528cf5.jpg) 就是这样

1. 信息太少, 譬如适用版本, os 等. 
2. 使用最新版本呢

**Comment by ping11700** [comment]
> 我也出现了此问题，可能是因为我在安装新版本的时候选择了覆盖之前旧文件安装，然后就出现了这个问题，同时我的键盘输入也变得很慢很卡。在我删除所有旧文件重新安装后就好了。

1.6.0 试了吗

**Comment by baonujuedoushi** [comment]
> > 我也出现了此问题，可能是因为我在安装新版本的时候选择了覆盖之前旧文件安装，然后就出现了这个问题，同时我的键盘输入也变得很慢很卡。在我删除所有旧文件重新安装后就好了。
> 
> 1.6.0 试了吗

我是1.5.0更新到1.6.0第一个版本的时候出现的。后来我安装新版本都是把旧文件全删了再安装，不会出现这个问题了
