### ISSUE TITLE
1.6.0版本 下载游戏 总是报 token失效 请先联系作者 下载不了

### ISSUE THREAD

**Issue by zh1011** [ping11700/LOLKit#29]

**Comment by ping11700** [comment]
2023-08-14 更新了文件, 是这版吗

**Comment by zh1011** [comment]
> 2023-08-14 更新了文件，是这个版本吗

就是github下载的最新版

**Comment by ping11700** [comment]
删除，在下载lolkit试试，租的国外服务器，节点不稳定可能。

**Comment by zh1011** [comment]
> 删除，在下载lolkit试试，租的国外服务器，节点不稳定可能。

能下载了 但是速度超级慢 我用wegame下载器下载了 10分钟就下下来了
