### ISSUE TITLE
能否增加一个手动输入账号密码的选项？

### ISSUE THREAD

**Issue by Doctorlee0827** [ping11700/LOLKit#33]
首先软件好评，精简掉不是必须得插件帧率提升了二十多帧，上个1.5的版本能正常使用自动登录，但是进去游戏拖动主窗口会强行回正，1.6版本后取消了这一点是好评的，但是自动登录在使用一段时间后无法正常使用了，账号和密码都无法输出，尝试重新软件和游戏都一样。

**Comment by ping11700** [comment]
请看一下视频介绍 合集

**Comment by Doctorlee0827** [comment]
> 请看一下视频介绍 合集

看过了合集最新1.6的，自动修复失败，详情[issue上有其他人有就不开了](https://github.com/ping11700/LOLKit/issues/34#issue-1876987138)，此外1.7是否已经更新，怎么releases上怎么没看到

**Comment by ping11700** [comment]
已更新, 已舍弃手动输入密码功能, 用扫码功能替代
