### ISSUE TITLE
无法使用自动登录

### ISSUE THREAD

**Issue by MOldtime** [ping11700/LOLKit#35]
重启过
路径没有中文
己关闭安全软件
LolKit版本：`1.7.0 2023-09-02` https://github.com/ping11700/LOLKit/commit/b3607be3d9882f94df6e5664aa79c941e026c256
已使用自动休复
![image](https://github.com/ping11700/LOLKit/assets/38435967/ecd2e69d-2114-478a-976e-8fc793bd7780)
Windows版本：
![image](https://github.com/ping11700/LOLKit/assets/38435967/402b25a5-027d-4aff-a2c4-6df67e4ecf38)
视频:

https://github.com/ping11700/LOLKit/assets/38435967/cf3b7ea8-42c7-4e58-ba8b-7f50b51adf91

**Comment by Doctorlee0827** [comment]
看下更新记录？已经弃用自动登陆了

**Comment by MOldtime** [comment]
> 看下更新记录？已经弃用自动登陆了

@Doctorlee0827
没啊，自动输入账号密码登录不一直是这个软件的特色吗？
而且修复列表也有修复自动输入

**Comment by MOldtime** [comment]
> 看下更新记录？已经弃用自动登陆了

扫码登陆后 我捕获到了 密码的输入

**Comment by MOldtime** [comment]
> 看下更新记录？已经弃用自动登陆了

https://github.com/ping11700/LOLKit/issues/33#issuecomment-1703849906
在issues中看到了，实在可惜，扫码固然安全，但实在繁琐

**Comment by ping11700** [comment]
没有舍弃自动登录

**Comment by MOldtime** [comment]
> 没有舍弃自动登录

好吧，这功能无法使用了，希望可以得到修复

**Comment by ping11700** [comment]
看了视频, 觉得有点不对劲, 没有自动选中qq登录呢, 方便的话, 加一下qq群看看

**Comment by MOldtime** [comment]
> 看了视频, 觉得有点不对劲, 没有自动选中qq登录呢, 方便的话, 加一下qq群看看

@ping11700 可能是我修改了自定义缩放吧 1080P 124
![image](https://github.com/ping11700/LOLKit/assets/38435967/8aa45db9-4107-41ef-a71b-04edc2a68930)

**Comment by ping11700** [comment]
这个没关系的，无关分辨率

**Comment by ping11700** [comment]
无关于分辨率，看视频上鼠标没有动，方便的话，可以远程debug看看

**Comment by MOldtime** [comment]
> 无关于分辨率，看视频上鼠标没有动，方便的话，可以远程debug看看

@ping11700  可以，我没找到qq群，可以发我一下吗

**Comment by ping11700** [comment]
这里不方便发，麻烦看一下b站，下面介绍都有

**Comment by MOldtime** [comment]
> 这里不方便发，麻烦看一下b站，下面介绍都有

ok

**Comment by MOldtime** [comment]
> 这里不方便发，麻烦看一下b站，下面介绍都有

已提交申请加入群聊
