### ISSUE TITLE
喜提一个小时封号，原因修改客户端

### ISSUE THREAD

**Issue by yu8349** [ping11700/LOLKit#36]
首先说，这个插件肯定没问题，是腾讯÷圣
在之前1.6的时候有时候就提示修改了客户端让我用重启客户端，终于在今天喜提一个小时

**Comment by MaintenanceStaff** [comment]
1.6和1.7都用过，没有遇到这种情况。

**Comment by ping11700** [comment]
感谢反馈, 发布一年多了, 在群里看到有两个小伙伴被封过, 然后一个是开了skin,另一个是被同学开了skin,

**Comment by yu8349** [comment]
> 感谢反馈, 发布一年多了, 在群里看到有两个小伙伴被封过, 一个是开了skin,另一个是被同学开了skin😂, 有没有可能是其他原因呢, 按照目前的功能设计来说, lol是无法感知lolkit的存在. tips:(lolClient经常误报各种问题, 不放心的话, 可以裸开lol对比一下哦)

我也不知道，不过误报是肯定的了，还给我qq什么的全掉了，我认为的流程是
启动软件->误报修改客户端，并且封号一小时->系统认为我qq被盗了，强行挤下去->让我改密码，才能登陆
还有一种可能是
我之前纯净启动的时候我记着好像把一个文件改成了只读，不过我一直纯净启动也没问题，用了插件也只提示过一两次，所以不是这个问题，应该是误报（他想让我用wegame）

**Comment by yu8349** [comment]
> 感谢反馈, 发布一年多了, 在群里看到有两个小伙伴被封过, 一个是开了skin,另一个是被同学开了skin😂, 有没有可能是其他原因呢, 按照目前的功能设计来说, lol是无法感知lolkit的存在. tips:(lolClient经常误报各种问题, 不放心的话, 可以裸开lol对比一下哦)

哦对了我可能忘了说了，腾讯是会检测你鼠标动作的，所以你用设定鼠标点的函数是会被检测的，包括我看1.7修复的时候有一个修复无法自动输入，无法自动输入我之前1.6没这个bug但是我最近退回到1.6就出现了，当然重点是把鼠标放进输入账户的框里面会提示有木马感染什么的
