### ISSUE TITLE
强制退出失败

### ISSUE THREAD

**Issue by yu8349** [ping11700/LOLKit#38]
如题，需要等五秒

**Comment by ping11700** [comment]
是最新包吗

**Comment by yu8349** [comment]
> 是最新包吗

是的，而且最近感觉帧数有的时候又掉回去了，感觉没清理那些插件一样，我删除又重新解压还是没用，不过我同学用1.6都可以，我最开始用1.6的时候也可以

**Comment by yu8349** [comment]
> 是最新包吗
你这个强退原理应该就是强制结束进程吧
有一次我客户端由于切屏bug退游戏之后变成了一个小黑框，然后我打开任务管理器，报出来一堆提示，好像是结束进程失败

**Comment by yu8349** [comment]
> 是最新包吗

你这个强退原理应该就是强制结束进程吧
有一次我客户端由于切屏bug退游戏之后变成了一个小黑框，然后我打开任务管理器，报出来一堆提示，好像是结束进程失败

**Comment by yu8349** [comment]
> 是最新包吗

最新消息，刚开了一把大乱斗，解压回了1.6版本，可以强退了

**Comment by ping11700** [comment]
v1.8.0

**Comment by ping11700** [comment]
done
