### ISSUE TITLE
自动修复——WG 失败

### ISSUE THREAD

**Issue by HeConnor** [ping11700/LOLKit#39]
win8, tool  version 1.7.0

自动修复时， 第二条 “修复无法跳过WG：失败“
同时有警告： 请求被终止，未能创建SSL/TLS安全通道

好像是打开该工具时，初始操作被阻止了，后续重启电脑，能打开工具，但是自动修复不能使用

**Comment by ping11700** [comment]
看一下trace, 一般无法修复, 是因为token过期了.

**Comment by HeConnor** [comment]
![2023-09-13_22-53-45](https://github.com/ping11700/LOLKit/assets/22026546/33e42adb-58fe-4e38-8cd4-8bcc3affa799)

**Comment by ping11700** [comment]
done
