### ISSUE TITLE
进入登录界面后，跳转到游戏检查更新界面

### ISSUE THREAD

**Issue by DeTahy** [ping11700/LOLKit#4]
点击登录后，总是会跳转到游戏检查更新界面，无法登录

**Comment by ping11700** [comment]
是否是lol需要更新呢？

**Comment by ping11700** [comment]
LOL有更新的话，点击lolkit“登录”，lolkit会监听LOL更新，lolkit监听到LOL更新完成后，就开始正常的登录流程了

**Comment by ping11700** [comment]
version1.4.0  done
