### ISSUE TITLE
提示安装wg

### ISSUE THREAD

**Issue by C-Hermit** [ping11700/LOLKit#46]
![JHS`I@L$O@56HLBD{RNP~}Y](https://github.com/ping11700/LOLKit/assets/138212753/f64c6766-27d9-4b30-9ba4-0bd0835e4b5f)
自动修复显示成功但是还是无法跳过

**Comment by ping11700** [comment]
远程Debug一下?

**Comment by C-Hermit** [comment]
> 远程Debug一下?

远程debug？什么意思不懂？

**Comment by ping11700** [comment]
在b站演示视频下方有群号，我远程看一下

**Comment by ping11700** [comment]
相同issue
