### ISSUE TITLE
help   

### ISSUE THREAD

**Issue by yangzhaoming1212** [ping11700/LOLKit#49]
启动过后，显示一下弹窗，请教一下作者这个如何解决 ，我是将原来LOL卸载，在LOLKit下载的版本，下载之后每一次启动就显示一下弹窗，导致我很久没有成功登录上去

读取配置文件d\game\lol小lol小tcls\config\commonconfig..cfg失败

**Comment by ping11700** [comment]
群里的小伙伴？done？

**Comment by ping11700** [comment]
LOLClient bug done
