### ISSUE TITLE
LOLKit.v2.0.1无法登录

### ISSUE THREAD

**Issue by wm13282041** [ping11700/LOLKit#51]
---------------------------
腾讯游戏登录程序
---------------------------
为了保障国家防沉迷通知相关要求的更好执行，登录组件统一升级到WeGame Launcher组件，请您通过游戏官网重新下载安装或者通过WeGame登录游戏
---------------------------
确定   
---------------------------
![image](https://github.com/ping11700/LOLKit/assets/12964581/a2d4de98-bb4f-4da2-bf67-6f59f8c9b24c)

**Comment by ping11700** [comment]
请看下方相同的issue

**Comment by ping11700** [comment]
重复issue
