### ISSUE TITLE
充值了，但是无法激活

### ISSUE THREAD

**Issue by SheldonAFK** [ping11700/LOLKit#52]
从官网下的，第一次充值了，激活，显示连接不上服务器。以为是下的有问题，删了重下，然后激活码变成新的，再次充值激活，还是不行

**Comment by SheldonAFK** [comment]
能不能告诉我一下，是本来现在就不用充值激活，还是有问题没激活成功

**Comment by ping11700** [comment]
能否提供一下单号

**Comment by SheldonAFK** [comment]
938602d3867147a99263c7a3ff37b920和2a2122f1a6eb423fb125b818f7516878

**Comment by SheldonAFK** [comment]
> 能否提供一下单号

938602d3867147a99263c7a3ff37b920 和 2a2122f1a6eb423fb125b818f7516878

**Comment by ping11700** [comment]
数据库里面有呢, 无法激活? 加群瞅瞅? 企鹅 922015662

**Comment by SheldonAFK** [comment]
> 数据库里面有呢, 无法激活? 加群瞅瞅? 企鹅 922015662

昨天登录显示激活了，但是我是不是相当于多充了10块钱呐。然后今天的话，打开一直没法连接服务器，我看那个记事本里显示token失效

**Comment by ping11700** [comment]
加群瞅瞅？,要是一个人充了两次。改一下数据库好了。
