### ISSUE TITLE
建议完善精简马服客户端的部分,修改国服首页.

### ISSUE THREAD

**Issue by idsasad** [ping11700/LOLKit#6]
https://www.bilibili.com/video/BV1s84y1x7ub/?spm_id_from=333.788.top_right_bar_window_history.content.click&vd_source=f502a261ff38f430a202c6f35e0b61b9
精简客户端的部分在视频45秒后
https://www.bilibili.com/video/BV1BG411E7YC/?spm_id_from=333.788.recommend_more_video.5&vd_source=f502a261ff38f430a202c6f35e0b61b9
这个是把国服的主页改成PBE的,会显示全英文的版本更新.

**Comment by ping11700** [comment]
赞, 后续优化

**Comment by ping11700** [comment]
done
