### ISSUE TITLE
为什么我用了这个之后，腾讯开始给我报网络不稳，好像被封机器🐎了？

### ISSUE THREAD

**Issue by Feynman1999** [ping11700/LOLKit#61]
如题

**Comment by Feynman1999** [comment]
应该不是巧合，之前没遇到过重连不了的情况

**Comment by ping11700** [comment]
连接不稳定也封号吗，没遇到过哎，
从lolkit设计和功能上说，不会导致连接不稳的😆.

**Comment by Feynman1999** [comment]
> 连接不稳定也封号吗，没遇到过哎， 从lolkit设计和功能上说，不会导致连接不稳的😆.

好的，目前还不清楚是因为什么，我是偶尔出现掉线

**Comment by ping11700** [comment]
close?
