### ISSUE TITLE
Win11 运行后键盘响应严重变慢

### ISSUE THREAD

**Issue by nightlanding** [ping11700/LOLKit#64]
RT，运行启动器并且启动游戏以后键盘输入出现1秒左右的延迟，与输入法无关，甚至游戏内的操作也会延迟。而且退出游戏和启动器后也不会恢复，需要去任务管理器找到LOLKit进程结束掉才会恢复。

**Comment by uf-hy** [comment]
我遇到了相同的问题, 我是在Windows10 22H2下遇到的

**Comment by jsutinbiber** [comment]
是嘛, 应该是偶现的, 我也是win11, 没感觉.

**Comment by ping11700** [comment]
远程debug看看?,  系统日志 发一下瞅瞅
