### ISSUE TITLE
已经赞助了，但经常加载不出来机器识别码，连不上服务器。

### ISSUE THREAD

**Issue by StarboWang** [ping11700/LOLKit#67]
<img width="376" alt="屏幕截图 2023-12-04 223209" src="https://github.com/ping11700/LOLKit/assets/51305634/d5a96c14-7922-4dc4-9cdb-1ff3e0cd00f8">

已经赞助了，但经常加载不出来机器识别码，连不上服务器。

**Comment by ping11700** [comment]
服务器已续租

**Comment by ping11700** [comment]
close?
