### ISSUE TITLE
win10下界面错乱

### ISSUE THREAD

**Issue by Kane-Kuroneko** [ping11700/LOLKit#68]
界面错乱

![image](https://github.com/ping11700/LOLKit/assets/40685018/c5bf57c9-f2da-4071-a8fc-fd7aa78cdf50)
![image](https://github.com/ping11700/LOLKit/assets/40685018/6da94071-3d68-4ea1-870c-af1c10145bf7)

**Comment by Kane-Kuroneko** [comment]
也许是因为系统设置里设置了放大 
![image](https://github.com/ping11700/LOLKit/assets/40685018/8463ffd9-98df-4fe3-b808-0e0b6b38dded)

**Comment by ping11700** [comment]
没考虑这个问题，后期处理一下

**Comment by ping11700** [comment]
还有这个问题吗

**Comment by Kane-Kuroneko** [comment]
> 还有这个问题吗

最近几个月弃坑LOL了哈，如果作者自测没问题的话我就close掉~
