### ISSUE TITLE
建议添加以下实用功能

### ISSUE THREAD

**Issue by skybbk1998** [ping11700/LOLKit#7]
一、添加“强行停止”按钮。关闭游戏客户端时需要过很久才能再次打开，很多时候只能去任务管理器强行停止，希望在LOLkit中添加快捷按钮。
二、添加“随LOL一同启动”选项。能自定义和LOL一起启动的软件，免的还要再去手动开启辅助软件（指的是基于官方api开发的类似战绩助手的辅助功能软件，非外挂），这样开机后只需要打开一个LOLkit，点一下开始游戏后等待一切加载就绪就能开始玩了。

**Comment by ping11700** [comment]
1.第一个没必要, 是进程占用, 等会儿就好了,或者在任务管理器中处理,  LOLkit来处理的话, 会导致误触,也不好管控.
2.第二个建议可以试试, 取决于用户接受程度.
