### ISSUE TITLE
用KIT登录突然提示实名认证出问题了，用wegame登录没有问题

### ISSUE THREAD

**Issue by xgyzz02** [ping11700/LOLKit#74]
用过自动修复，第一次还有用，之后就没用了，输入密码登录提示实名认证出问题，扫码也提示实名认证有问题，wegame登录没问题。
![QQ图片20240110221101](https://github.com/ping11700/LOLKit/assets/156208648/2bfde570-9c58-4225-aff9-d9be23ee4844)
wegame登录正常
![Uploading 2.png…]()

**Comment by xgyzz02** [comment]
![2](https://github.com/ping11700/LOLKit/assets/156208648/681badcb-1b39-4be4-be36-bcab89188cb5)

**Comment by ping11700** [comment]
不是lolkit的问题, 裸登就知道了.
