### ISSUE TITLE
新版本报毒

### ISSUE THREAD

**Issue by 74587** [ping11700/LOLKit#76]
已检测:Trojan:Win32/Wacatac.B!ml
详细信息:这个程序很危险，而且执行来自攻击者的命令。

**Comment by 74587** [comment]
> 已检测:Trojan:Win32/Wacatac.B!ml 详细信息:这个程序很危险，而且执行来自攻击者的命令。

**Comment by cbsfwc** [comment]
windows defender报毒, 正常操作.
