### ISSUE TITLE
新版本挂后台有几率导致游戏内键盘监听失灵

### ISSUE THREAD

**Issue by EKKOJQ** [ping11700/LOLKit#79]
表现为在对局中按下QWER等功能键时延迟2~3s,同时鼠标和游戏画面正常运转.经多次排查后,网络正常,键盘硬件正常,关闭LOLkit进程后按键正常响应.

**Comment by ping11700** [comment]
未曾遇到过...

**Comment by ping11700** [comment]
估计很难解决这样的问题, 可以远程debug一下

**Comment by EKKOJQ** [comment]
我看之前issue里也有人提到过,群里也有人反应跟我有一样的情况,现在我复现是复现不出来了,这几天没碰到了,我那天早中晚连续碰到4把.我把其中一局录像发群里你看看,这里最多只能传10M.
