### ISSUE TITLE
装备不能应用到对局+无法查询召唤师信息

### ISSUE THREAD

**Issue by EKKOJQ** [ping11700/LOLKit#81]
![image](https://github.com/ping11700/LOLKit/assets/97377143/b785be0d-32d3-40ab-8b0e-f1bcd8f8014a)
日志报错
'''11:03:04[Info]: ************* LOLKit启动 *************
11:03:05[Info]: 自动检测到游戏路径: f:\program files (x86)\英雄联盟(26)\lol\lol\英雄联盟\tcls\client.exe
11:03:08[Error]-Flow_Lcu.Start: can't read right token and port
   在 JDcwHMH6FcLdPkEAR8dA.xNDxtcH6iqZKU7fQtj3y.<<Start>b__1_0>d.MoveNext()
11:03:14[Error]-Flow_Lcu.Start: can't read right token and port
   在 JDcwHMH6FcLdPkEAR8dA.xNDxtcH6iqZKU7fQtj3y.<<Start>b__1_0>d.MoveNext()
11:03:19[Error]-Flow_Lcu.Start: can't read right token and port
   在 JDcwHMH6FcLdPkEAR8dA.xNDxtcH6iqZKU7fQtj3y.<<Start>b__1_0>d.MoveNext()
11:03:24[Error]-Flow_Lcu.Start: can't read right token and port
   在 JDcwHMH6FcLdPkEAR8dA.xNDxtcH6iqZKU7fQtj3y.<<Start>b__1_0>d.MoveNext()
11:03:30[Error]-Flow_Lcu.Start: can't read right token and port
   在 JDcwHMH6FcLdPkEAR8dA.xNDxtcH6iqZKU7fQtj3y.<<Start>b__1_0>d.MoveNext()
11:03:35[Error]-Flow_Lcu.Start: can't read right token and port
   在 JDcwHMH6FcLdPkEAR8dA.xNDxtcH6iqZKU7fQtj3y.<<Start>b__1_0>d.MoveNext()
11:03:40[Error]-Flow_Lcu.Start: can't read right token and port
   在 JDcwHMH6FcLdPkEAR8dA.xNDxtcH6iqZKU7fQtj3y.<<Start>b__1_0>d.MoveNext()
11:03:46[Error]-Flow_Lcu.Start: can't read right token and port
   在 JDcwHMH6FcLdPkEAR8dA.xNDxtcH6iqZKU7fQtj3y.<<Start>b__1_0>d.MoveNext()
11:03:51[Error]-Flow_Lcu.Start: can't read right token and port
   在 JDcwHMH6FcLdPkEAR8dA.xNDxtcH6iqZKU7fQtj3y.<<Start>b__1_0>d.MoveNext()
11:03:56[Error]-Flow_Lcu.Start: can't read right token and port
   在 JDcwHMH6FcLdPkEAR8dA.xNDxtcH6iqZKU7fQtj3y.<<Start>b__1_0>d.MoveNext()
11:04:01[Error]-Flow_Lcu.Start: can't read right token and port
   在 JDcwHMH6FcLdPkEAR8dA.xNDxtcH6iqZKU7fQtj3y.<<Start>b__1_0>d.MoveNext()
11:04:06[Error]-Flow_Lcu.Start: can't read right token and port
   在 JDcwHMH6FcLdPkEAR8dA.xNDxtcH6iqZKU7fQtj3y.<<Start>b__1_0>d.MoveNext()
11:04:13[Error]-connect: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:5979
11:04:13[Error]-WebSocket OnClose: 1006 An exception has occurred while connecting.
11:04:18[Error]-startReceiving: The opcode of a frame is not supported.
11:04:18[Error]-WebSocket OnClose: 1003 An exception has occurred while receiving.
11:04:20[Error]-WebsocketService.SendMessage: The current state of the interface is not Open.
   在 uXYDoIvDidUf9xYjKR5.xjGjCHv5nJiTFm5Qkvb.Send(String data)
   在 xhIPNoH50nDKGvsh0jSq.SPqxFGH5MO6HBG3O7T1u.<<SendMessage>b__19_0>d.MoveNext()
11:04:24[Error]-startReceiving: The opcode of a frame is not supported.
11:04:24[Error]-WebSocket OnClose: 1003 An exception has occurred while receiving.
11:04:26[Error]-WebsocketService.SendMessage: The current state of the interface is not Open.
   在 uXYDoIvDidUf9xYjKR5.xjGjCHv5nJiTFm5Qkvb.Send(String data)
   在 xhIPNoH50nDKGvsh0jSq.SPqxFGH5MO6HBG3O7T1u.<<SendMessage>b__19_0>d.MoveNext()
11:04:33[Error]-startReceiving: The opcode of a frame is not supported.
11:04:33[Error]-WebSocket OnClose: 1003 An exception has occurred while receiving.
11:04:33[Error]-WebsocketService.SendMessage: The current state of the interface is not Open.
   在 uXYDoIvDidUf9xYjKR5.xjGjCHv5nJiTFm5Qkvb.Send(String data)
   在 xhIPNoH50nDKGvsh0jSq.SPqxFGH5MO6HBG3O7T1u.<<SendMessage>b__19_0>d.MoveNext()
11:06:49[Error]-startReceiving: The opcode of a frame is not supported.
11:06:49[Error]-WebSocket OnClose: 1003 An exception has occurred while receiving.
11:06:50[Error]-WebsocketService.SendMessage: The current state of the interface is not Open.
   在 uXYDoIvDidUf9xYjKR5.xjGjCHv5nJiTFm5Qkvb.Send(String data)
   在 xhIPNoH50nDKGvsh0jSq.SPqxFGH5MO6HBG3O7T1u.<<SendMessage>b__19_0>d.MoveNext()
11:23:38[Error]-startReceiving: The opcode of a frame is not supported.
11:23:38[Error]-WebSocket OnClose: 1003 An exception has occurred while receiving.
11:23:39[Error]-WebsocketService.SendMessage: The current state of the interface is not Open.
   在 uXYDoIvDidUf9xYjKR5.xjGjCHv5nJiTFm5Qkvb.Send(String data)
   在 xhIPNoH50nDKGvsh0jSq.SPqxFGH5MO6HBG3O7T1u.<<SendMessage>b__19_0>d.MoveNext()
11:34:18[Error]-startReceiving: The opcode of a frame is not supported.
11:34:18[Error]-WebSocket OnClose: 1003 An exception has occurred while receiving.
'

**Comment by ping11700** [comment]
1. API不支持模糊搜索, 需要全称+#xxxx, 
2. log没有"装备不能应用到对局"的信息
3. log报的错误为lolclient未启动.

**Comment by EKKOJQ** [comment]
召唤师查询那个没问题了,但是装备确实不能应用到对局,群里的人都不能,是不是我们操作方法不对

**Comment by ping11700** [comment]
周末的时候, 我再多多debug一下.

**Comment by YBxbxxz** [comment]
装备确实不能应用

**Comment by dalianhaowano** [comment]
我的可以哎, 2.2.0版本

**Comment by ping11700** [comment]
已查到原因, 下个版本修复.
