### ISSUE TITLE
一开始挺快的，几十上百m下载，下到一半掉到1mb每秒，然后到几十kb每秒，

### ISSUE THREAD

**Issue by jkben39** [ping11700/LOLKit#84]
- ![IMG20240401153739.jpg](https://github.com/ping11700/LOLKit/assets/125142686/76390433-f534-4d01-845e-64b90b24cefc)

**Comment by jkben39** [comment]
![IMG20240401153739.jpg](https://github.com/ping11700/LOLKit/assets/125142686/9525c12f-d46e-46df-b5b9-4bad5610328b)

**Comment by fengyutongji** [comment]
我的一直很稳定, 带宽跑满了!!!,  ( ఠൠఠ )ﾉ

**Comment by ping11700** [comment]
因素: 有线下载, 磁盘读写, 本地运营商大流量检测等.

**Comment by Zyb-iot** [comment]
太卡了

**Comment by lingxiao99** [comment]
我也是一半后就慢下来了
