### ISSUE TITLE
LOLKit致使输入卡顿

### ISSUE THREAD

**Issue by TofuWorkshop** [ping11700/LOLKit#87]
无关输入法，无关输入场景，重启也不行。CPU占用也不高，但是输入就是很卡有延迟，大概和蓝牙键盘没电了/距离远了那种感觉差不多。（但其实不论蓝牙还是有线都这样）

前三次稳定复现，一打开就卡一关闭就好，但是最后一次想录gif做附件的时候反而没法复现出来了。但还是得提一下有这个现象。

**Comment by ping11700** [comment]
下个版本 优化
