### ISSUE TITLE
未拥有的英雄不能添加到秒选吗

### ISSUE THREAD

**Issue by 1219099256** [ping11700/LOLkit#98]
有时遇到周免就没法抢了

**Comment by ping11700** [comment]
请附带文件(截图, 录屏)

**Comment by 1219099256** [comment]
![image](https://github.com/ping11700/LOLKit/assets/63403797/0fa3eca5-0755-4cc8-99b5-45211ed2e4d6)
这里厄斐琉斯就是暗的，无法添加

**Comment by 1219099256** [comment]
![image](https://github.com/ping11700/LOLKit/assets/63403797/143de655-1f9a-45b5-995f-8a8ef101db23)
you'fa又发现炸弹人我也没有，也不再周免里，但是可以添加，有点奇怪

**Comment by ping11700** [comment]
周免分为经典模式, 大乱斗模式.

**Comment by aaronkaiyangg** [comment]
> 周免分为经典模式, 大乱斗模式.

你好，我反馈一个情况，设置大乱斗里优选英雄以此为ABCD且都在待选区，此时软件会秒选A，但当我手动选取B后，又会立即秒选回A，能否在优选英雄设置界面加一个小开关按钮，来应对此情况（玩家应该会经常出现想玩自己设置的次优先级英雄的情况）。

**Comment by ping11700** [comment]
remove 首位

**Comment by aaronkaiyangg** [comment]
邮件已收到，会尽快回复，谢谢！
